### ISSUE TITLE
entering the wrong card crashes the server

### ISSUE THREAD

**Issue by dominictarr** [nearform/well#1]
```
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at Seneca.defaultresponder (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:884:11)
    at respond (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:815:21)
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:1253:18
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:1253:18
    at args.(anonymous function) (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:398:14)
    at Seneca.self.fail (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:691:14)
    at Seneca.sd.fail (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:401:24)
    at Seneca.<anonymous> (/Users/dominictarr/c/well/well.js:447:28)
2013-07-30T15:39:59.589Z    ERROR   act err kldthn  Cannot call method 'toString' of undefined  9qxv26      at ServerResponse.writeHead (http.js:1161:45)
2013-07-30T15:39:59.590Z    ERROR   fail    seneca/act_error    Seneca: Cannot call method 'toString' of undefined      at ServerResponse.writeHead (http.js:1161:45)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at ServerResponse.res.end (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/logger.js:148:13)
    at Seneca.<anonymous> (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/session.js:286:13)
    at Seneca.<anonymous> (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:1270:16)
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:1270:16
    at do_save (/Users/dominictarr/c/well/node_modules/seneca/plugin/mem-store.js:121:9)
    at Seneca.store.save (/Users/dominictarr/c/well/node_modules/seneca/plugin/mem-store.js:107:12)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:731:32
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:970:27
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:188:13)
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:185:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:731:32
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:970:27
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:188:13)
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:185:15)
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:185:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:731:32
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:970:27
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:188:13)
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:185:15)
    at pass (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:190:11)
2013-07-30T15:39:59.596Z    ERROR   act err caxnzi  Cannot call method 'toString' of undefined  jm6ncl      at ServerResponse.writeHead (http.js:1161:45)
2013-07-30T15:39:59.596Z    ERROR   fail    seneca/act_error    Seneca: Cannot call method 'toString' of undefined      at ServerResponse.writeHead (http.js:1161:45)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:731:32
    at /Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:970:27
    at param (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:188:13)
    at pass (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:190:11)
    at router (/Users/dominictarr/c/well/node_modules/seneca/lib/http-router.js:196:7)
2013-07-30T15:39:59.598Z    ERROR   act err jzdj03  Cannot call method 'toString' of undefined  jm6ncl      at ServerResponse.writeHead (http.js:1161:45)
2013-07-30T15:39:59.598Z    ERROR   fail    seneca/act_error    Seneca: Cannot call method 'toString' of undefined      at ServerResponse.writeHead (http.js:1161:45)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/session.js:313:9)
    at /Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/session.js:337:9
    at Seneca.<anonymous> (/Users/dominictarr/c/well/well.js:714:9)
    at Seneca.<anonymous> (/Users/dominictarr/c/well/node_modules/seneca/lib/seneca.js:1270:16)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.json [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/json.js:56:55)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.methodOverride [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at multipart (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/multipart.js:70:58)
    at /Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at multipart (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/multipart.js:70:58)
    at /Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
    at urlencoded (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:54:72)
    at /Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.query [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.cookieParser [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.cookieParser [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.logger (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/logger.js:156:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.logger (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/logger.js:156:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.expressInit [as handle] (/Users/dominictarr/c/well/node_modules/express/lib/middleware.js:31:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.expressInit [as handle] (/Users/dominictarr/c/well/node_modules/express/lib/middleware.js:31:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.query [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Object.query [as handle] (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/middleware/query.js:44:5)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:198:3)
    at Server.app (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/connect.js:65:37)
uncaughtException: Cannot call method 'toString' of undefined
TypeError: Cannot call method 'toString' of undefined
    at ServerResponse.writeHead (http.js:1161:45)
    at ServerResponse.res.writeHead (/Users/dominictarr/c/well/node_modules/seneca/node_modules/connect/lib/patch.js:75:22)
    at ServerResponse._implicitHeader (http.js:1112:8)
    at ServerResponse.OutgoingMessage.end (http.js:860:10)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:149:13)
    at next (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:195:7)
    at Function.app.handle (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/proto.js:198:3)
    at Server.app (/Users/dominictarr/c/well/node_modules/express/node_modules/connect/lib/connect.js:65:37)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2051:12)

```

**Comment by YooJaSung** [comment]
how solve this problem ?? 
i get same error
