### ISSUE TITLE
TypeError: sessionstore is not a function

### ISSUE THREAD

**Issue by hszhai** [nearform/well#13]
Upon trying to start, the following error appeared:
`icezees-MacBook-Pro:well icezee$ node app.js --env=development --seneca.log=plugin:well
uncaughtException: sessionstore is not a function
TypeError: sessionstore is not a function
    at Object.<anonymous> (/Users/icezee/TM/seneca/well/app.js:143:50)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
`

Thanks for taking time reviewing this!

**Comment by akeelnazir** [comment]
+1
